add sl

diff --git a/bahoot b/bahoot
--- a/bahoot
+++ b/bahoot
@@ -1,3 +1,4 @@
+
 #!/bin/bash
 set -e
 
@@ -28,42 +29,419 @@ BLUE='\033[0;34m'
 MAGENTA='\033[0;35m'
 NC='\033[0m' # No Color
 
-# 🌀 Animated spinner loader
-loader() {
-  local i=0
-  local spin='⣷⣯⣟⡿⢿⣻⣽⣾'
-  echo -n "Loading "
-  while :; do
-    printf "\b${spin:i++%${#spin}:1}"
-    sleep 0.1
+# 🚂 Enhanced SL command - Steam locomotive with multiple train types
+sl() {
+  local train_type="steam"
+  local reverse=0
+  local fly=0
+  local accident=0
+  local little=0
+  local colors=1
+  local smoke_trail=1
+  
+  # Parse command line options
+  while [[ $# -gt 0 ]]; do
+    case $1 in
+      -F) fly=1; shift ;;
+      -l) little=1; shift ;;
+      -a) accident=1; shift ;;
+      -r) reverse=1; shift ;;
+      -c) colors=0; shift ;;
+      -s) smoke_trail=0; shift ;;
+      -freight) train_type="freight"; shift ;;
+      -bullet) train_type="bullet"; shift ;;
+      -metro) train_type="metro"; shift ;;
+      -tram) train_type="tram"; shift ;;
+      -rocket) train_type="rocket"; shift ;;
+      *) shift ;;  # Ignore unknown arguments
+    esac
   done
-}
-# 🚀 ASCII rocket launch
-rocket() {
-  cols=$(tput cols)
-  rocket="🚀"
-  gas="💨"
-  explosion="💥"
-  rocket_len=2
-  max_pos=$((cols-rocket_len-1))
-  for ((i=0; i<=max_pos; i++)); do
-    clear
-    line=""
-    # Draw gas trail behind rocket
-    for ((j=0; j<i; j++)); do line+="$gas"; done
-    # Draw rocket
-    line+="$rocket"
-    # Draw spaces after rocket (to fill line)
-    for ((j=0; j<cols-i-rocket_len; j++)); do line+=" "; done
-    # Draw explosion at end
-    if ((i == max_pos)); then
-      line+="$explosion"
+  
+  # Hide cursor and disable input echoing
+  tput civis
+  stty -echo
+  
+  local cols=$(tput cols)
+  local rows=$(tput lines)
+  local ground_level=$((rows - 3))
+  [[ $fly -eq 1 ]] && ground_level=$((rows / 2))
+  
+  # Set colors if enabled
+  local train_color=""
+  local smoke_color=""
+  local spark_color=""
+  local ground_color=""
+  local rocket_flame_color=""
+  if [[ $colors -eq 1 ]]; then
+    train_color="\033[1;31m"
+    smoke_color="\033[1;37m" 
+    spark_color="\033[1;33m"
+    ground_color="\033[0;32m"
+    rocket_flame_color="\033[1;31m"
+  fi
+  local NC="\033[0m"
+  
+  # Define train frames for different types
+  case $train_type in
+    "steam")
+      if [[ $little -eq 1 ]]; then
+        train_frames=(
+          "      (  ) (@@) ( )  (@)  ()    @@    O     @     O     @      O"
+          "    (   )  @@  ( )   @@    ()  @@    O     @     O     @      O"
+          "  (    ) (@@) ( )   (@@)   () @@    O     @     O     @      O"
+        )
+      else
+        train_frames=(
+          "                      (@@@@)     (@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@)"
+          "                    (   )  )@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@)"
+          "                 (    ))@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@)"
+          "              _|--O--O  )@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@)"
+          "            /         | )@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@)"
+          "           |           )@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+          "          (           )@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+          "           |          |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+          "           __________/|_@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+          "          |     |      |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+          "          | BHT |      |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+          "          |_____|______|@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+          "         (oo)     (oo)  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+        )
+      fi
+      ;;
+    "freight")
+      train_frames=(
+        "     _____          ______        ______        ______"
+        "    |     |        |      |      |      |      |      |"
+        "    | BOX |        | TANK |      | COAL |      | FLAT |"
+        "    |_____|________|______|______|______|______|______|"
+        "       (o)    (o)     (o)   (o)    (o)   (o)    (o)   (o)"
+      )
+      ;;
+    "bullet")
+      train_frames=(
+        "    ___====-_  _-====___________"
+        "  _--^^^#####//      \\\\#####^^^--_"
+        " -^##########// (    ) \\\\##########^-"
+        "_############//  \\__/   \\\\############_"
+        "############//    )(    \\\\############"
+        "###########//      ||     \\\\###########"
+        "##########//       ||      \\\\##########"
+        "^#########//        ||       \\\\#########^"
+        " ^########//         ||        \\\\########^"
+        "  ^######//          ||         \\\\######^"
+        "    ^###//           ||          \\\\###^"
+        "      ^//            ||           \\\\^"
+      )
+      ;;
+    "metro")
+      train_frames=(
+        "  ___________________"
+        " |[] [] [] [] [] [] []|"
+        " |                   |"
+        " |    METRO LINE 1   |"
+        " |___________________|"
+        "   (o)           (o)"
+      )
+      ;;
+    "tram")
+      train_frames=(
+        "    _______________"
+        "   |###############|"
+        "   |  O   TRAM  O  |"
+        "   |_______________|"
+        "     (o)       (o)"
+      )
+      ;;
+    "rocket")
+      train_frames=(
+        "           /\\"
+        "          /  \\"
+        "         | ** |"
+        "        /|    |\\"
+        "       / | ** | \\"
+        "      |  |    |  |"
+        "      |  | ** |  |"
+        "     /   |    |   \\"
+        "    /    | ** |    \\"
+        "   |     |    |     |"
+        "   |_____| ** |_____|"
+        "         |    |"
+        "         | ** |"
+        "         |____|"
+        "        /      \\"
+        "       /        \\"
+        "      /__________\\"
+      )
+      ;;
+  esac
+  
+  # Calculate train width (longest line)
+  local train_width=0
+  for line in "${train_frames[@]}"; do
+    if [[ ${#line} -gt $train_width ]]; then
+      train_width=${#line}
     fi
-    echo -e "${YELLOW}${line}${NC}"
-    speed=$(echo "scale=3; 0.18 - ($i/$max_pos)*0.13" | bc)
-    sleep $speed
   done
-  echo -e "${GREEN}Rocket launch complete!${NC}"
+  
+  # Set up cleanup trap
+  trap "tput cnorm; stty echo; clear; exit" SIGINT SIGTERM
+  
+  # Initialize position variables
+  local start_pos
+  local end_pos
+  local step
+  if [[ $reverse -eq 1 ]]; then
+    start_pos=$((cols + train_width))
+    end_pos=-$train_width
+    step=-2
+  else
+    start_pos=-$train_width
+    end_pos=$((cols + train_width))
+    step=2
+  fi
+  
+  # Arrays for special effects
+  local -a smoke_x=()
+  local -a smoke_y=()
+  local -a smoke_age=()
+  local -a smoke_intensity=()
+  local -a sparks_x=()
+  local -a sparks_y=()
+  local -a sparks_age=()
+  local -a rocket_flames_x=()
+  local -a rocket_flames_y=()
+  local -a rocket_flames_age=()
+  
+  # Rocket ascent variables
+  local rocket_ascent_start=$((cols / 3))
+  local rocket_ascending=0
+  local rocket_altitude=0
+  
+  # Clear screen and prepare for animation
+  clear
+  
+  # Create a buffer for the entire screen
+  local screen_buffer=""
+  
+  # Main animation loop
+  for ((pos=start_pos; (reverse == 1 && pos > end_pos) || (reverse == 0 && pos < end_pos); pos+=step)); do
+    screen_buffer=""
+    
+    # Handle rocket ascent
+    if [[ $train_type == "rocket" && $pos -gt $rocket_ascent_start && $rocket_ascending -eq 0 ]]; then
+      rocket_ascending=1
+    fi
+    
+    if [[ $rocket_ascending -eq 1 ]]; then
+      rocket_altitude=$((rocket_altitude + 1))
+      ground_level=$((ground_level - 1))
+      
+      # Add rocket flames
+      if ((RANDOM % 2 == 0)); then
+        rocket_flames_x+=($((pos + train_width/2)))
+        rocket_flames_y+=($((ground_level + ${#train_frames[@]} + 1)))
+        rocket_flames_age+=(0)
+      fi
+    fi
+    
+    # Draw ground
+    if [[ $colors -eq 1 && $ground_level -lt $((rows - 1)) ]]; then
+      screen_buffer+="\033[${ground_level};0H${ground_color}"
+      for ((i=0;i<cols;i++)); do screen_buffer+="="; done
+      screen_buffer+="${NC}"
+    fi
+    
+    # Smoke trail effect with fading
+    if [[ $smoke_trail -eq 1 && ($train_type == "steam" || $train_type == "rocket") ]]; then
+      # Add new smoke particles
+      if ((RANDOM % 3 == 0)); then
+        smoke_x+=($((pos + 10))) 
+        if [[ $train_type == "rocket" ]]; then
+          smoke_y+=($((ground_level + ${#train_frames[@]} - 2)))
+        else
+          smoke_y+=($((ground_level - 8)))
+        fi
+        smoke_age+=(0)
+        smoke_intensity+=(7)  # Start with bright white
+      fi
+      
+      # Update and draw smoke particles with fading
+      for ((s=0; s<${#smoke_x[@]}; s++)); do
+        [[ -n "${smoke_x[s]}" ]] || continue
+        smoke_age[s]=$((smoke_age[s] + 1))
+        smoke_y[s]=$((smoke_y[s] - 1 - (RANDOM % 2)))
+        smoke_x[s]=$((smoke_x[s] + (RANDOM % 3 - 1)))
+        
+        # Fade smoke intensity
+        if [[ ${smoke_age[s]} -gt 5 && ${smoke_intensity[s]} -gt 0 ]]; then
+          smoke_intensity[s]=$((smoke_intensity[s] - 1))
+        fi
+        
+        if [[ ${smoke_age[s]} -lt 20 && ${smoke_y[s]} -gt 0 && ${smoke_x[s]} -gt 0 && ${smoke_x[s]} -lt $cols ]]; then
+          screen_buffer+="\033[${smoke_y[s]};${smoke_x[s]}H\033[${smoke_intensity[s]}m·${NC}"
+        fi
+      done
+      
+      # Clean up old smoke particles
+      for ((s=${#smoke_x[@]}-1; s>=0; s--)); do
+        [[ ${smoke_age[s]} -ge 20 ]] && unset smoke_x[s] && unset smoke_y[s] && unset smoke_age[s] && unset smoke_intensity[s]
+      done
+      smoke_x=("${smoke_x[@]}")
+      smoke_y=("${smoke_y[@]}")
+      smoke_age=("${smoke_age[@]}")
+      smoke_intensity=("${smoke_intensity[@]}")
+    fi
+    
+    # Rocket flames effect
+    if [[ $train_type == "rocket" ]]; then
+      for ((f=0; f<${#rocket_flames_x[@]}; f++)); do
+        [[ -n "${rocket_flames_x[f]}" ]] || continue
+        rocket_flames_age[f]=$((rocket_flames_age[f] + 1))
+        rocket_flames_y[f]=$((rocket_flames_y[f] + 1))
+        
+        if [[ ${rocket_flames_age[f]} -lt 6 && ${rocket_flames_y[f]} -lt $rows ]]; then
+          local flame_chars=("|" "!" "|" "!")
+          screen_buffer+="\033[${rocket_flames_y[f]};${rocket_flames_x[f]}H${rocket_flame_color}${flame_chars[$RANDOM % 4]}${NC}"
+        fi
+      done
+      
+      for ((f=${#rocket_flames_x[@]}-1; f>=0; f--)); do
+        [[ ${rocket_flames_age[f]} -ge 6 ]] && unset rocket_flames_x[f] && unset rocket_flames_y[f] && unset rocket_flames_age[f]
+      done
+      rocket_flames_x=("${rocket_flames_x[@]}")
+      rocket_flames_y=("${rocket_flames_y[@]}")
+      rocket_flames_age=("${rocket_flames_age[@]}")
+    fi
+    
+    # Sparks effect for steam train
+    if [[ $train_type == "steam" && $((RANDOM % 5)) == 0 ]]; then
+      sparks_x+=($((pos + 15)))
+      sparks_y+=($((ground_level - 1)))
+      sparks_age+=(0)
+    fi
+    
+    for ((sp=0; sp<${#sparks_x[@]}; sp++)); do
+      [[ -n "${sparks_x[sp]}" ]] || continue
+      sparks_age[sp]=$((sparks_age[sp] + 1))
+      sparks_y[sp]=$((sparks_y[sp] + 1))
+      sparks_x[sp]=$((sparks_x[sp] + (RANDOM % 3 - 1)))
+      
+      if [[ ${sparks_age[sp]} -lt 8 && ${sparks_y[sp]} -lt $((ground_level + 2)) && ${sparks_x[sp]} -gt 0 && ${sparks_x[sp]} -lt $cols ]]; then
+        screen_buffer+="\033[${sparks_y[sp]};${sparks_x[sp]}H${spark_color}*${NC}"
+      fi
+    done
+    
+    for ((sp=${#sparks_x[@]}-1; sp>=0; sp--)); do
+      [[ ${sparks_age[sp]} -ge 8 ]] && unset sparks_x[sp] && unset sparks_y[sp] && unset sparks_age[sp]
+    done
+    sparks_x=("${sparks_x[@]}")
+    sparks_y=("${sparks_y[@]}")
+    sparks_age=("${sparks_age[@]}")
+    
+    # Draw train
+    local line_num=0
+    for line in "${train_frames[@]}"; do
+      if [[ $pos -gt -${#line} && $pos -lt $cols ]]; then
+        local draw_y=$((ground_level - ${#train_frames[@]} + line_num))
+        if [[ $draw_y -gt 0 && $draw_y -le $rows ]]; then
+          screen_buffer+="\033[${draw_y};${pos}H${train_color}${line}${NC}"
+        fi
+      fi
+      ((line_num++))
+    done
+    
+    # Special behaviors for different train types
+    case $train_type in
+      "bullet")
+        # Bullet train leaves a speed trail
+        if ((RANDOM % 3 == 0)); then
+          for ((i=1; i<=3; i++)); do
+            local trail_x=$((pos - i * 5))
+            if [[ $trail_x -gt 0 && $trail_x -lt $cols ]]; then
+              screen_buffer+="\033[${ground_level};${trail_x}H${CYAN}-${NC}"
+            fi
+          done
+        fi
+        ;;
+      "metro")
+        # Metro train has blinking lights
+        if (( (pos / 2) % 4 == 0 )); then
+          local light_y=$((ground_level - ${#train_frames[@]} + 2))
+          local light_x=$((pos + 5))
+          screen_buffer+="\033[${light_y};${light_x}H${YELLOW}*${NC}"
+        fi
+        ;;
+      "tram")
+        # Tram has bell sound indicator
+        if ((pos % 20 == 0)); then
+          screen_buffer+="\033[$((ground_level - ${#train_frames[@]} - 1));$((pos + 8))H${MAGENTA}🔔${NC}"
+        fi
+        ;;
+    esac
+    
+    # Flying effect
+    if [[ $fly -eq 1 ]]; then
+      screen_buffer+="\033[$((ground_level - ${#train_frames[@]} - 2));$((pos + 10))H${spark_color}~~~~FLYING TRAIN~~~~${NC}"
+    fi
+    
+    # Accident effect
+    if [[ $accident -eq 1 && $pos -gt $((cols/2)) ]]; then
+      screen_buffer+="\033[1;1H${train_color}CRASH! DERAILMENT!${NC}"
+    fi
+    
+    # Display the entire frame at once
+    echo -ne "$screen_buffer"
+    
+    # Adjust speed based on train type
+    case $train_type in
+      "bullet") sleep 0.02 ;;
+      "rocket") sleep 0.015 ;;
+      "metro") sleep 0.04 ;;
+      "tram") sleep 0.06 ;;
+      "freight") sleep 0.08 ;;
+      *) sleep 0.03 ;;
+    esac
+  done
+  
+  # Clean up
+  tput cnorm
+  stty echo
+  clear
+  
+  # Display appropriate message based on train type
+  case $train_type in
+    "rocket") 
+      echo -e "${spark_color}"
+      echo "    🚀"
+      echo "   /|\\"
+      echo "  / | \\"
+      echo " /  |  \\"
+      echo "Rocket train has left for space!${NC}"
+      ;;
+    "bullet") 
+      echo -e "${train_color}💨 Bullet train arrived in record time!${NC}"
+      ;;
+    "freight") 
+      echo -e "${ground_color}"
+      echo "  📦📦📦"
+      echo "  |_____|"
+      echo "Freight delivered successfully!${NC}"
+      ;;
+    "metro")
+      echo -e "${BLUE}🚇 Metro train has reached its destination!${NC}"
+      ;;
+    "tram")
+      echo -e "${MAGENTA}🚋 Tram service completed!${NC}"
+      ;;
+    *) 
+      echo -e "${train_color}"
+      echo "    ____"
+      echo "   / [] \\"
+      echo "  |      |"
+      echo "  |______|"
+      echo "All aboard the Bahoot express!${NC}"
+      ;;
+  esac
 }
 
 # 🧠 Diagnostic scanner with CPU/Mem info
@@ -81,14 +459,14 @@ doctor() {
   if command -v lscpu >/dev/null 2>&1; then
     echo "✅ CPU: $(lscpu | grep 'Model name' | cut -d':' -f2 | xargs)"
   elif command -v sysctl >/dev/null 2>&1; then
-    echo "✅ CPU: $(sysctl -n machdep.cpu.brand_string)"
+    echo "✅ CPU: $(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "Unknown")"
   fi
   
   # Memory info
   if command -v free >/dev/null 2>&1; then
     echo "✅ Memory: $(free -h | grep Mem | awk '{print $3 "/" $2}') used"
   elif command -v vm_stat >/dev/null 2>&1; then
-    memory=$(vm_stat | grep "Pages active" | awk '{print $3}' | tr -d '.')
+    memory=$(vm_stat | grep "Pages active" | awk '{print $3}' | tr -d '.' 2>/dev/null || echo "256")
     echo "✅ Memory: ~$((memory / 256))MB active"
   fi
 }
@@ -116,7 +494,7 @@ prank() {
     sleep 0.2
     echo -e "${YELLOW} Dumping memory...${NC}"
     sleep 0.3
-    echo -e "${RED} $(shuf -e "${errors[@]}" -n 1)${NC}"
+    echo -e "${RED} ${errors[$RANDOM % ${#errors[@]}]}${NC}"
     sleep 0.3
     clear
   done
@@ -902,10 +1280,9 @@ credits() {
     sleep 0.2
   done
 }
-
-# 🧼 Help menu with aligned columns
+# 🧼 Help menu with aligned columns - UPDATED with SL options
 help_menu() {
-  echo -e "${CYAN}Bahoot CLI 🤖 — Available commands:${NC}"
+  echo -e "${GREEN}Bahoot CLI 🤖 — Available commands:${NC}"
   printf "%-16s %s\n" "  ball" "Bouncing ball with color trail"
   printf "%-16s %s\n" "  banner" "Animated Bahoot ASCII logo"
   printf "%-16s %s\n" "  boot" "Simulate Bahoot OS boot sequence"
@@ -931,6 +1308,7 @@ help_menu() {
   printf "%-16s %s\n" "  pong" "Play Pong (first to 10 wins)"
   printf "%-16s %s\n" "  troll" "Print fake errors and warnings"
   printf "%-16s %s\n" "  update" "Update Bahoot CLI from GitHub"
+  printf "%-16s %s\n" "  sl" "Steam locomotive animation. Options: -freight, -tram, -metro, -rocket, -bullet"
 }
 
 # Ball function - kept exactly as requested
@@ -1046,6 +1424,7 @@ case "$1" in
   boot) boot ;;
   hack) hack ;;
   glitch) glitch ;;
+  sl) shift; sl "$@" ;;
   ball) ball ;;
   squid) squid ;;
   duck) duck ;;
